### ISSUE TITLE
Cannot install bot

### ISSUE THREAD

**Issue by ahhardesty** [hdmifish/petal#4]
Followed the Windows install instructions and got this:

![error](https://cloud.githubusercontent.com/assets/9207909/22057371/39b7bd0e-dd19-11e6-8e96-be0aa9294464.png)

**Comment by hdmifish** [comment]
Ah, this happens sometimes based on how you save the file. You have two options, the safer way is to copy the contents into a new document and save it on your own device that way it is Self-signed. Or simply do `Set-ExecutionPolicy Unrestricted`
