### ISSUE TITLE
Text issue?

### ISSUE THREAD

**Issue by Mazszy** [hdmifish/petal#7]
Still removes desired amount (I ask to remove 10, it removes 10) but it keeps adding 3 to its statement...

![93054c00e9be4bbdba57fe303a54a140](https://cloud.githubusercontent.com/assets/25642209/22791517/7931e1da-ee9e-11e6-977d-d9c202db9556.png)

**Comment by hdmifish** [comment]
This is on purpose. 

notice that you have to type 2 messages and petal types one.
That's 3 plus whatever you wanted to delete.

**Comment by Mazszy** [comment]
Oh, thanks for clearing that up :)

I was sure it hadn't been like that before so I was thrown off.
